- name: Apply openshift terraform plan
  terraform:
    project_path: "{{ role_path }}/files"
    backend_config:
      path: "{{ role_path }}/../../.state/az_ocp_infra/{{ ocp_cluster_name }}/terraform.tfstate"
    force_init: true
    variables:
      azure_resource_group_name: "{{ az_resource_group_name }}"
      cluster_name: "{{ ocp_cluster_name }}"
      cluster_location: "{{ az_location }}"
      cluster_network_name: "{{ az_network_name }}"
      cluster_subnetwork_name: "{{ az_subnetwork_name }}"
      rhcos_image_url: "{{ rhcos_image_url }}"
      ignition_dir: "{{ ignition_dir }}"
      bootstrap_vm_size: "{{ boostrap_vm_size }}"
      master_vm_size: "{{ master_vm_size }}"
      master_vm_count: "{{ master_vm_count }}"
      worker_vm_size: "{{ worker_vm_size }}"
      worker_vm_count: "{{ worker_vm_count }}"
      dns_zone_name: "{{ az_dns_zone_name }}"
      az_client_id: "{{ az_client_id }}"
      az_subscription_id: "{{ az_subscription_id }}"
      az_tenant_id: "{{ az_tenant_id }}"
    register: apply_ocp