- name: Apply openshift terraform plan
  terraform:
    project_path: "{{ role_path }}/files"
    backend_config:
      resource_group_name: "{{ tf_backend_resource_group_name }}"
      storage_account_name: "{{ tf_backend_storage_account_name }}"
      container_name: "{{ tf_backend_container_name }}"
      client_id: "{{ tf_backend_client_id }}"
      client_secret: "{{ tf_backend_client_secret }}"
      subscription_id: "{{ tf_backend_subscription_id }}"
      tenant_id: "{{ tf_backend_tenant_id }}"
    force_init: true
    variables:
      az_resource_group_name: "{{ az_resource_group_name }}"
      az_client_id: "{{ az_client_id }}"
      az_client_secret: "{{ az_client_secret }}"
      az_subscription_id: "{{ az_subscription_id }}"
      az_tenant_id: "{{ az_tenant_id }}"
      az_location: "{{ az_location }}"
      az_network_name: "{{ az_network_name }}"
      az_network_resource_group_name: "{{ az_network_resource_group_name }}"
      az_subnetwork_name: "{{ az_subnetwork_name }}"
      az_dns_zone_name: "{{ az_dns_zone_name }}"
      az_dns_zone_resource_group_name: "{{ az_dns_zone_resource_group_name }}"
      az_rhcos_image_id: "{{ az_rhcos_image_id }}"
      ocp_cluster_name: "{{ ocp_cluster_name }}"
      ocp_ignition_dir: "{{ ocp_ignition_dir }}"
      ocp_bootstrap_vm_size: "{{ ocp_bootstrap_vm_size }}"
      ocp_bootstrap_replicas: "{{ ocp_bootstrap_replicas }}"
      ocp_master_vm_size: "{{ ocp_master_vm_size }}"
      ocp_worker_vm_size: "{{ ocp_worker_vm_size }}"
      ocp_worker_replicas: "{{ ocp_worker_replicas }}"
    workspace: "{{ ocp_cluster_name }}"