- name: Create ignition directory
  file:
    state: directory
    path: "{{ ocp_ignition_dir }}"

- name: Create install-config.yaml
  template:
    src: "{{ role_path }}/templates/install-config.yaml.j2"
    dest: "{{ ocp_ignition_dir }}/install-config.yaml"

- name: Generate ignition files
  shell: "openshift-install
          create ignition-configs
          --dir='{{ ocp_ignition_dir }}'"
  args:
    creates: "{{ ocp_ignition_dir }}/bootstrap.ign"