- name: Create state directory
  file:
    state: directory
    path: "{{ role_path }}/../../.state/ocp_ignition/{{ ocp_cluster_name }}"

- name: Create install-config.yaml
  template:
    src: "{{ role_path }}/templates/install-config.yaml.j2"
    dest: "{{ role_path }}/../../.state/ocp_ignition/{{ ocp_cluster_name }}/install-config.yaml"

- name: Generate ignition files
  shell: "openshift-install
          create ignition-configs
          --dir='{{ role_path }}/../../.state/ocp_ignition/{{ ocp_cluster_name }}'"
  args:
    creates: "{{ role_path }}/../../.state/ocp_ignition/{{ ocp_cluster_name }}/bootstrap.ign"