- name: Create ignition directory
  file:
    state: directory
    path: "{{ ocp_ignition_dir }}"

- name: Create install-config.yaml
  template:
    src: "{{ role_path }}/templates/install-config.yaml.j2"
    dest: "{{ ocp_ignition_dir }}/install-config.yaml"

# This is needed because pods on masters aren't reachable by the ingress
# It can likely be removed in future version (>4.2)
# and we can generate ignition files directly
# https://docs.openshift.com/container-platform/4.2/installing/installing_bare_metal/installing-bare-metal.html#installation-user-infra-generate-k8s-manifest-ignition_installing-bare-metal
- name: Generate installation manifests
  shell: "openshift-install
          create manifests
          --dir='{{ ocp_ignition_dir }}'"
  args:
    creates: "{{ ocp_ignition_dir }}/manifests/cluster-scheduler-02-config.yml"

- name: Set masters as unschedulable
  lineinfile:
    path: "{{ ocp_ignition_dir }}/manifests/cluster-scheduler-02-config.yml"
    regexp: '^\s{2}mastersSchedulable:\strue$'
    line: "  mastersSchedulable: false"

- name: Set ingress controller replica count
  lineinfile:
    path: "{{ ocp_ignition_dir }}/manifests/cluster-ingress-02-config.yml"
    insertafter: '^\s{2}domain:\s.*$'
    line: "  replicas: {{ ocp_worker_replicas }}"

- name: Generate ignition files
  shell: "openshift-install
          create ignition-configs
          --dir='{{ ocp_ignition_dir }}'"
  args:
    creates: "{{ ocp_ignition_dir }}/bootstrap.ign"