#!/usr/bin/env ansible-playbook
---
- name: "{{ teardown | default(false) | ternary('Teardown', 'Deploy') }} openshift infrastructure"
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
  - name: Generate ignition files and store them in azure
    import_role:
      name: openshift_azure_storage_ignition
    tags:
    - never
    - openshift_azure_storage_ignition

  - name: Deploy rhcos image into azure resource group
    import_role:
      name: openshift_azure_rhcos_image
    tags:
    - never
    - openshift_azure_rhcos_image

  - name: Deploy openshift cluster into azure
    import_role:
      name: openshift_azure_cluster
    tags:
    - never
    - openshift_azure_cluster
