#!/usr/bin/env ansible-playbook
---
- name: "{{ teardown | default(false) | ternary('Teardown', 'Deploy') }} openshift infrastructure"
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
  - name: Generate ignition files
    import_role:
      name: openshift_azure_storage_ignition
    tags:
    - never
    - openshift_azure_storage_ignition

  - name: Deploy rhcos image
    import_role:
      name: az_ocp_rhcos_image
    tags:
    - never
    - az_ocp_rhcos_image

  - name: Deploy azure infrastructure
    import_role:
      name: az_ocp_infra
    tags:
    - never
    - az_ocp_infra
