#!/usr/bin/env ansible-playbook
---
- name: Deploy / teardown OpenShift components
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
  - name: Generate ignition files
    import_role:
      name: ocp_ignition
    tags:
    - never
    - ocp_ignition

  - name: Deploy RHCOS image
    import_role:
      name: az_ocp_rhcos_image
    tags:
    - never
    - az_ocp_rhcos_image

  - name: Deploy Azure infrastructure
    import_role:
      name: az_ocp_infra
    tags:
    - never
    - az_ocp_infra
